(function() {var implementors = {};
implementors["fusionner"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"fusionner/merger/struct.Note.html\" title=\"struct fusionner::merger::Note\">Note</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"fusionner/merger/struct.Merge.html\" title=\"struct fusionner::merger::Merge\">Merge</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"fusionner/merger/enum.ShouldMergeResult.html\" title=\"enum fusionner::merger::ShouldMergeResult\">ShouldMergeResult</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"fusionner/git/struct.RemoteHead.html\" title=\"struct fusionner::git::RemoteHead\">RemoteHead</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"fusionner/git/struct.RefspecStr.html\" title=\"struct fusionner::git::RefspecStr\">RefspecStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"fusionner/struct.RepositoryConfiguration.html\" title=\"struct fusionner::RepositoryConfiguration\">RepositoryConfiguration</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"fusionner/struct.Password.html\" title=\"struct fusionner::Password\">Password</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"fusionner/struct.WatchReferences.html\" title=\"struct fusionner::WatchReferences\">WatchReferences</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
